version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ~/.docker-data/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres-db-network

networks:
  postgres-db-network:
    driver: bridge
